# FlashAttention 2 split runners and analysis modes.

FA2_MK := $(lastword $(MAKEFILE_LIST))

FA2_DIR = $(TEST_SRC_DIR)/fa2
FA2_TEST_SOURCE = $(FA2_DIR)/fa2_fwd_fp16_test.cu
FA2_VARIANTS = h32d64_full h32d64_causal h16d128_full h16d128_causal
FA2_STANDARD_PROFILES = smoke small medium large
FA2_PROFILES = $(FA2_STANDARD_PROFILES) breakdown scaling concurrency

FA2_BREAKDOWN_MODES = baseline skip_cp_async skip_mma skip_softmax fma_softmax only_mma only_cp_async only_softmax nothing
FA2_SCALING_MODES = baseline nothing only_cp_async only_softmax only_mma softmax_mma
FA2_CONCURRENCY_MODES = only_cp_async only_cp_async_bhhalf qk_softmax_pv_only qk_pv_only

# A workload recipe is instantiated only for architectures whose TOML manifest
# lists the FA2 source. The compiler target always comes from that manifest.
FA2_ARCHITECTURES := $(foreach arch,$(ARCHITECTURES),$(if $(filter fa2,$(ARCH_TEST_GROUPS_$(arch))),$(arch)))
$(foreach arch,$(FA2_ARCHITECTURES),\
  $(eval WORKLOAD_MANAGED_TEST_GROUPS_$(arch) += fa2))
FA2_NVCCFLAGS = $(BASE_NVCCFLAGS) -arch=$(ARCH_NVCC_TARGET_$(FA2_TARGET_ARCH))

define FA2_STANDARD_OBJECTS_FOR
$(foreach variant,$(FA2_VARIANTS),$(OBJ_DIR)/$(1)/fa2/$(2)_$(variant)/fa2_fwd_fp16_test.cu.o)
endef

define FA2_STANDARD_TARGETS_FOR
$(foreach variant,$(FA2_VARIANTS),$(BIN_DIR)/$(1)/fa2/$(2)_$(variant)_tests)
endef

define FA2_MODE_OBJECTS_FOR
$(foreach mode,$(3),$(OBJ_DIR)/$(1)/fa2/$(2)_$(mode)/fa2_fwd_fp16_test.cu.o)
endef

define FA2_MODE_TARGETS_FOR
$(foreach mode,$(3),$(BIN_DIR)/$(1)/fa2/$(2)_$(mode)_tests)
endef

define REGISTER_FA2_ARCH_VARIABLES
FA2_SMOKE_OBJECTS_$(1) := $(call FA2_STANDARD_OBJECTS_FOR,$(1),smoke)
FA2_SMALL_OBJECTS_$(1) := $(call FA2_STANDARD_OBJECTS_FOR,$(1),small)
FA2_MEDIUM_OBJECTS_$(1) := $(call FA2_STANDARD_OBJECTS_FOR,$(1),medium)
FA2_LARGE_OBJECTS_$(1) := $(call FA2_STANDARD_OBJECTS_FOR,$(1),large)
FA2_BREAKDOWN_OBJECTS_$(1) := $(call FA2_MODE_OBJECTS_FOR,$(1),breakdown,$(FA2_BREAKDOWN_MODES))
FA2_SCALING_OBJECTS_$(1) := $(call FA2_MODE_OBJECTS_FOR,$(1),scaling,$(FA2_SCALING_MODES))
FA2_CONCURRENCY_OBJECTS_$(1) := $(call FA2_MODE_OBJECTS_FOR,$(1),concurrency,$(FA2_CONCURRENCY_MODES))
FA2_OBJECTS_$(1) := $$(FA2_SMOKE_OBJECTS_$(1)) $$(FA2_SMALL_OBJECTS_$(1)) \
  $$(FA2_MEDIUM_OBJECTS_$(1)) $$(FA2_LARGE_OBJECTS_$(1)) \
  $$(FA2_BREAKDOWN_OBJECTS_$(1)) $$(FA2_SCALING_OBJECTS_$(1)) \
  $$(FA2_CONCURRENCY_OBJECTS_$(1))

FA2_SMOKE_TARGETS_$(1) := $(call FA2_STANDARD_TARGETS_FOR,$(1),smoke)
FA2_SMALL_TARGETS_$(1) := $(call FA2_STANDARD_TARGETS_FOR,$(1),small)
FA2_MEDIUM_TARGETS_$(1) := $(call FA2_STANDARD_TARGETS_FOR,$(1),medium)
FA2_LARGE_TARGETS_$(1) := $(call FA2_STANDARD_TARGETS_FOR,$(1),large)
FA2_BREAKDOWN_TARGETS_$(1) := $(call FA2_MODE_TARGETS_FOR,$(1),breakdown,$(FA2_BREAKDOWN_MODES))
FA2_SCALING_TARGETS_$(1) := $(call FA2_MODE_TARGETS_FOR,$(1),scaling,$(FA2_SCALING_MODES))
FA2_CONCURRENCY_TARGETS_$(1) := $(call FA2_MODE_TARGETS_FOR,$(1),concurrency,$(FA2_CONCURRENCY_MODES))

TEST_GROUP_PROFILES_$(1)_fa2 := $(FA2_PROFILES)
TEST_GROUP_PROFILE_MODES_$(1)_fa2_breakdown := $(FA2_BREAKDOWN_MODES) all
TEST_GROUP_PROFILE_MODES_$(1)_fa2_scaling := $(FA2_SCALING_MODES) all
TEST_GROUP_PROFILE_MODES_$(1)_fa2_concurrency := $(FA2_CONCURRENCY_MODES) all
endef
$(foreach arch,$(FA2_ARCHITECTURES),$(eval $(call REGISTER_FA2_ARCH_VARIABLES,$(arch))))

define REGISTER_FA2_STANDARD_PROFILE
TEST_GROUP_BUILD_TARGET_$(1)_fa2_$(2) := fa2-$(1)-$(2)
TEST_GROUP_BINARY_GROUP_$(1)_fa2_$(2) := fa2-$(1)-$(2)
TEST_GROUP_EXECUTOR_$(1)_fa2_$(2) := gtest-multi
TEST_GROUP_FILTER_$(1)_fa2_$(2) := *
FA2_BINARY_GROUPS += fa2-$(1)-$(2)
BINARY_GROUP_BINARIES_fa2-$(1)-$(2) = $$(FA2_$(3)_TARGETS_$(1))
.PHONY: fa2-$(1)-$(2)
fa2-$(1)-$(2): setup-gtest $$(FA2_$(3)_TARGETS_$(1))
endef

$(foreach arch,$(FA2_ARCHITECTURES), \
  $(eval $(call REGISTER_FA2_STANDARD_PROFILE,$(arch),smoke,SMOKE)) \
  $(eval $(call REGISTER_FA2_STANDARD_PROFILE,$(arch),small,SMALL)) \
  $(eval $(call REGISTER_FA2_STANDARD_PROFILE,$(arch),medium,MEDIUM)) \
  $(eval $(call REGISTER_FA2_STANDARD_PROFILE,$(arch),large,LARGE)))

define REGISTER_FA2_MODE
TEST_GROUP_BUILD_TARGET_$(1)_fa2_$(2)_$(3) := fa2-$(1)-$(2)-$(3)
TEST_GROUP_BINARY_GROUP_$(1)_fa2_$(2)_$(3) := fa2-$(1)-$(2)-$(3)
TEST_GROUP_EXECUTOR_$(1)_fa2_$(2)_$(3) := gtest-multi
TEST_GROUP_FILTER_$(1)_fa2_$(2)_$(3) := *
FA2_BINARY_GROUPS += fa2-$(1)-$(2)-$(3)
BINARY_GROUP_BINARIES_fa2-$(1)-$(2)-$(3) := $(BIN_DIR)/$(1)/fa2/$(2)_$(3)_tests
.PHONY: fa2-$(1)-$(2)-$(3)
fa2-$(1)-$(2)-$(3): setup-gtest $(BIN_DIR)/$(1)/fa2/$(2)_$(3)_tests
endef

$(foreach arch,$(FA2_ARCHITECTURES), \
  $(foreach mode,$(FA2_BREAKDOWN_MODES),$(eval $(call REGISTER_FA2_MODE,$(arch),breakdown,$(mode)))) \
  $(foreach mode,$(FA2_SCALING_MODES),$(eval $(call REGISTER_FA2_MODE,$(arch),scaling,$(mode)))) \
  $(foreach mode,$(FA2_CONCURRENCY_MODES),$(eval $(call REGISTER_FA2_MODE,$(arch),concurrency,$(mode)))))

define REGISTER_FA2_ALL_MODE
TEST_GROUP_BUILD_TARGET_$(1)_fa2_$(2)_all := fa2-$(1)-$(2)
TEST_GROUP_BINARY_GROUP_$(1)_fa2_$(2)_all := fa2-$(1)-$(2)
TEST_GROUP_EXECUTOR_$(1)_fa2_$(2)_all := build-only
TEST_GROUP_FILTER_$(1)_fa2_$(2)_all := *
FA2_BINARY_GROUPS += fa2-$(1)-$(2)
BINARY_GROUP_BINARIES_fa2-$(1)-$(2) = $$(FA2_$(3)_TARGETS_$(1))
.PHONY: fa2-$(1)-$(2)
fa2-$(1)-$(2): setup-gtest $$(FA2_$(3)_TARGETS_$(1))
endef

$(foreach arch,$(FA2_ARCHITECTURES), \
  $(eval $(call REGISTER_FA2_ALL_MODE,$(arch),breakdown,BREAKDOWN)) \
  $(eval $(call REGISTER_FA2_ALL_MODE,$(arch),scaling,SCALING)) \
  $(eval $(call REGISTER_FA2_ALL_MODE,$(arch),concurrency,CONCURRENCY)))

BINARY_GROUPS += $(FA2_BINARY_GROUPS)

FA2_ALL_OBJECTS := $(foreach arch,$(FA2_ARCHITECTURES),$(FA2_OBJECTS_$(arch)))
$(foreach arch,$(FA2_ARCHITECTURES),$(eval $(FA2_OBJECTS_$(arch)): FA2_TARGET_ARCH := $(arch)))

FA2_COMMON_FLAGS = --ftemplate-backtrace-limit=0 -O3 \
                          --use_fast_math \
                          -lineinfo --expt-relaxed-constexpr \
                          --expt-extended-lambda \
                          -DNDEBUG \
                          -DCUTE_SM90_EXTENDED_MMA_SHAPES_ENABLED \
                          -I$(FA2_DIR) \
                          $(FLASH_ATTENTION_FA2_INCLUDES)
FA2_FLAGS = $(FA2_COMMON_FLAGS)

# Each standard object instantiates one D/full-causal kernel family.
FA2_H32D64_FULL_FLAGS = -DFA2_PREFILL_ENABLE_H32D64_FULL
FA2_H32D64_CAUSAL_FLAGS = -DFA2_PREFILL_ENABLE_H32D64_CAUSAL
FA2_H16D128_FULL_FLAGS = -DFA2_PREFILL_ENABLE_H16D128_FULL
FA2_H16D128_CAUSAL_FLAGS = -DFA2_PREFILL_ENABLE_H16D128_CAUSAL

define FA2_CASE_OBJECTS
$(foreach arch,$(FA2_ARCHITECTURES),$(OBJ_DIR)/$(arch)/fa2/$(1)/fa2_fwd_fp16_test.cu.o)
endef

$(call FA2_CASE_OBJECTS,smoke_h32d64_full): TEST_GROUP_EXTRA_NVCCFLAGS = $(FA2_FLAGS) -DFA2_PREFILL_GROUP_SMOKE $(FA2_H32D64_FULL_FLAGS)
$(call FA2_CASE_OBJECTS,smoke_h32d64_causal): TEST_GROUP_EXTRA_NVCCFLAGS = $(FA2_FLAGS) -DFA2_PREFILL_GROUP_SMOKE $(FA2_H32D64_CAUSAL_FLAGS)
$(call FA2_CASE_OBJECTS,smoke_h16d128_full): TEST_GROUP_EXTRA_NVCCFLAGS = $(FA2_FLAGS) -DFA2_PREFILL_GROUP_SMOKE $(FA2_H16D128_FULL_FLAGS)
$(call FA2_CASE_OBJECTS,smoke_h16d128_causal): TEST_GROUP_EXTRA_NVCCFLAGS = $(FA2_FLAGS) -DFA2_PREFILL_GROUP_SMOKE $(FA2_H16D128_CAUSAL_FLAGS)
$(call FA2_CASE_OBJECTS,small_h32d64_full): TEST_GROUP_EXTRA_NVCCFLAGS = $(FA2_FLAGS) -DFA2_PREFILL_GROUP_SMALL $(FA2_H32D64_FULL_FLAGS)
$(call FA2_CASE_OBJECTS,small_h32d64_causal): TEST_GROUP_EXTRA_NVCCFLAGS = $(FA2_FLAGS) -DFA2_PREFILL_GROUP_SMALL $(FA2_H32D64_CAUSAL_FLAGS)
$(call FA2_CASE_OBJECTS,small_h16d128_full): TEST_GROUP_EXTRA_NVCCFLAGS = $(FA2_FLAGS) -DFA2_PREFILL_GROUP_SMALL $(FA2_H16D128_FULL_FLAGS)
$(call FA2_CASE_OBJECTS,small_h16d128_causal): TEST_GROUP_EXTRA_NVCCFLAGS = $(FA2_FLAGS) -DFA2_PREFILL_GROUP_SMALL $(FA2_H16D128_CAUSAL_FLAGS)
$(call FA2_CASE_OBJECTS,medium_h32d64_full): TEST_GROUP_EXTRA_NVCCFLAGS = $(FA2_FLAGS) -DFA2_PREFILL_GROUP_MEDIUM $(FA2_H32D64_FULL_FLAGS)
$(call FA2_CASE_OBJECTS,medium_h32d64_causal): TEST_GROUP_EXTRA_NVCCFLAGS = $(FA2_FLAGS) -DFA2_PREFILL_GROUP_MEDIUM $(FA2_H32D64_CAUSAL_FLAGS)
$(call FA2_CASE_OBJECTS,medium_h16d128_full): TEST_GROUP_EXTRA_NVCCFLAGS = $(FA2_FLAGS) -DFA2_PREFILL_GROUP_MEDIUM $(FA2_H16D128_FULL_FLAGS)
$(call FA2_CASE_OBJECTS,medium_h16d128_causal): TEST_GROUP_EXTRA_NVCCFLAGS = $(FA2_FLAGS) -DFA2_PREFILL_GROUP_MEDIUM $(FA2_H16D128_CAUSAL_FLAGS)
$(call FA2_CASE_OBJECTS,large_h32d64_full): TEST_GROUP_EXTRA_NVCCFLAGS = $(FA2_FLAGS) -DFA2_PREFILL_GROUP_LARGE $(FA2_H32D64_FULL_FLAGS)
$(call FA2_CASE_OBJECTS,large_h32d64_causal): TEST_GROUP_EXTRA_NVCCFLAGS = $(FA2_FLAGS) -DFA2_PREFILL_GROUP_LARGE $(FA2_H32D64_CAUSAL_FLAGS)
$(call FA2_CASE_OBJECTS,large_h16d128_full): TEST_GROUP_EXTRA_NVCCFLAGS = $(FA2_FLAGS) -DFA2_PREFILL_GROUP_LARGE $(FA2_H16D128_FULL_FLAGS)
$(call FA2_CASE_OBJECTS,large_h16d128_causal): TEST_GROUP_EXTRA_NVCCFLAGS = $(FA2_FLAGS) -DFA2_PREFILL_GROUP_LARGE $(FA2_H16D128_CAUSAL_FLAGS)

FA2_BREAKDOWN_FLAGS = $(FA2_FLAGS) -DFA2_PREFILL_GROUP_BREAKDOWN $(FA2_H16D128_FULL_FLAGS) -DFA2_FWD_SENS_FORCE_H100_HDIM128
$(call FA2_CASE_OBJECTS,breakdown_baseline): TEST_GROUP_EXTRA_NVCCFLAGS = $(FA2_BREAKDOWN_FLAGS)
$(call FA2_CASE_OBJECTS,breakdown_skip_cp_async): TEST_GROUP_EXTRA_NVCCFLAGS = $(FA2_BREAKDOWN_FLAGS) -DFA2_FWD_SENS_SKIP_CP_ASYNC
$(call FA2_CASE_OBJECTS,breakdown_skip_mma): TEST_GROUP_EXTRA_NVCCFLAGS = $(FA2_BREAKDOWN_FLAGS) -DFA2_FWD_SENS_SKIP_MMA
$(call FA2_CASE_OBJECTS,breakdown_skip_softmax): TEST_GROUP_EXTRA_NVCCFLAGS = $(FA2_BREAKDOWN_FLAGS) -DFA2_FWD_SENS_SKIP_SOFTMAX
$(call FA2_CASE_OBJECTS,breakdown_fma_softmax): TEST_GROUP_EXTRA_NVCCFLAGS = $(FA2_BREAKDOWN_FLAGS) -DFA2_FWD_SENS_FMA_SOFTMAX
$(call FA2_CASE_OBJECTS,breakdown_only_mma): TEST_GROUP_EXTRA_NVCCFLAGS = $(FA2_BREAKDOWN_FLAGS) -DFA2_FWD_SENS_SKIP_CP_ASYNC -DFA2_FWD_SENS_SKIP_SOFTMAX
$(call FA2_CASE_OBJECTS,breakdown_only_cp_async): TEST_GROUP_EXTRA_NVCCFLAGS = $(FA2_BREAKDOWN_FLAGS) -DFA2_FWD_SENS_SKIP_MMA -DFA2_FWD_SENS_SKIP_SOFTMAX
$(call FA2_CASE_OBJECTS,breakdown_only_softmax): TEST_GROUP_EXTRA_NVCCFLAGS = $(FA2_BREAKDOWN_FLAGS) -DFA2_FWD_SENS_SKIP_CP_ASYNC -DFA2_FWD_SENS_SKIP_MMA
$(call FA2_CASE_OBJECTS,breakdown_nothing): TEST_GROUP_EXTRA_NVCCFLAGS = $(FA2_BREAKDOWN_FLAGS) -DFA2_FWD_SENS_SKIP_CP_ASYNC -DFA2_FWD_SENS_SKIP_MMA -DFA2_FWD_SENS_SKIP_SOFTMAX

FA2_SCALING_FLAGS = $(FA2_FLAGS) -DFA2_PREFILL_GROUP_SCALING $(FA2_H16D128_FULL_FLAGS) $(FA2_H16D128_CAUSAL_FLAGS) -DFA2_FWD_SENS_FORCE_H100_HDIM128
$(call FA2_CASE_OBJECTS,scaling_baseline): TEST_GROUP_EXTRA_NVCCFLAGS = $(FA2_SCALING_FLAGS)
$(call FA2_CASE_OBJECTS,scaling_nothing): TEST_GROUP_EXTRA_NVCCFLAGS = $(FA2_SCALING_FLAGS) -DFA2_FWD_SENS_SKIP_CP_ASYNC -DFA2_FWD_SENS_SKIP_MMA -DFA2_FWD_SENS_SKIP_MMA_OPERANDS -DFA2_FWD_SENS_SKIP_SOFTMAX
$(call FA2_CASE_OBJECTS,scaling_only_cp_async): TEST_GROUP_EXTRA_NVCCFLAGS = $(FA2_SCALING_FLAGS) -DFA2_FWD_SENS_SKIP_MMA -DFA2_FWD_SENS_SKIP_MMA_OPERANDS -DFA2_FWD_SENS_SKIP_SOFTMAX
$(call FA2_CASE_OBJECTS,scaling_only_softmax): TEST_GROUP_EXTRA_NVCCFLAGS = $(FA2_SCALING_FLAGS) -DFA2_FWD_SENS_SKIP_CP_ASYNC -DFA2_FWD_SENS_SKIP_MMA -DFA2_FWD_SENS_SKIP_MMA_OPERANDS
$(call FA2_CASE_OBJECTS,scaling_only_mma): TEST_GROUP_EXTRA_NVCCFLAGS = $(FA2_SCALING_FLAGS) -DFA2_FWD_SENS_SKIP_CP_ASYNC -DFA2_FWD_SENS_SKIP_SOFTMAX
$(call FA2_CASE_OBJECTS,scaling_softmax_mma): TEST_GROUP_EXTRA_NVCCFLAGS = $(FA2_SCALING_FLAGS) -DFA2_FWD_SENS_SKIP_CP_ASYNC

FA2_CONCURRENCY_FLAGS = $(FA2_FLAGS) -DFA2_PREFILL_GROUP_CONCURRENCY $(FA2_H16D128_FULL_FLAGS) -DFA2_FWD_SENS_FORCE_H100_HDIM128
$(call FA2_CASE_OBJECTS,concurrency_only_cp_async): TEST_GROUP_EXTRA_NVCCFLAGS = $(FA2_CONCURRENCY_FLAGS) -DFA2_FWD_SENS_SKIP_MMA -DFA2_FWD_SENS_SKIP_MMA_OPERANDS -DFA2_FWD_SENS_SKIP_SOFTMAX
$(call FA2_CASE_OBJECTS,concurrency_only_cp_async_bhhalf): TEST_GROUP_EXTRA_NVCCFLAGS = $(FA2_CONCURRENCY_FLAGS) -DFA2_PREFILL_CONCURRENCY_BH_HALF -DFA2_FWD_SENS_SKIP_MMA -DFA2_FWD_SENS_SKIP_MMA_OPERANDS -DFA2_FWD_SENS_SKIP_SOFTMAX -DFA2_FWD_CTA_PROFILE
$(call FA2_CASE_OBJECTS,concurrency_qk_softmax_pv_only): TEST_GROUP_EXTRA_NVCCFLAGS = $(FA2_CONCURRENCY_FLAGS) -DFA2_FWD_SENS_SKIP_CP_ASYNC
$(call FA2_CASE_OBJECTS,concurrency_qk_pv_only): TEST_GROUP_EXTRA_NVCCFLAGS = $(FA2_CONCURRENCY_FLAGS) -DFA2_FWD_SENS_SKIP_CP_ASYNC -DFA2_FWD_SENS_SKIP_SOFTMAX

$(FA2_ALL_OBJECTS): $(FA2_TEST_SOURCE) $(TEST_HEADERS) \
$(TOP_MAKEFILE) $(FA_MK) $(FA2_MK) \
$(FLASH_ATTENTION_PREPARED_STAMP) | $(OBJ_DIR)
	@mkdir -p $(dir $@)
	$(NVCC) $(FA2_NVCCFLAGS) $(TEST_GROUP_EXTRA_NVCCFLAGS) \
		$(INCLUDES) $(GPGPUSIM_FLAGS) -c $< -o $@

define REGISTER_FA2_LINK_RULE
$$(BIN_DIR)/$(1)/fa2/%_tests: \
$$(OBJ_DIR)/$(1)/fa2/%/fa2_fwd_fp16_test.cu.o $$(OBJ_DIR)/gtest_main.a \
$$(TOP_MAKEFILE) $$(FA2_MK) | $$(BIN_DIR)
	@mkdir -p $$(dir $$@)
	$$(CXX) $$(CXXFLAGS) $$(filter-out $$(TOP_MAKEFILE) $$(FA2_MK),$$^) \
		-o $$@ -lpthread $$(CUDA_LIBS)
endef
$(foreach arch,$(FA2_ARCHITECTURES),$(eval $(call REGISTER_FA2_LINK_RULE,$(arch))))
