// Standalone launcher for Triton kernel: {{KERNEL_NAME}}
// Generated by Tracker
// Kernel hash: {{KERNEL_HASH}}
// NOTE: This is a template. Use the launch-specific harness for actual argument data.

#include <cuda.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#define CUDA_CHECK(call) \
    do { \
        CUresult err = call; \
        if (err != CUDA_SUCCESS) { \
            const char* errStr; \
            cuGetErrorString(err, &errStr); \
            fprintf(stderr, "CUDA error at %s:%d - %s\n", \
                    __FILE__, __LINE__, errStr); \
            exit(1); \
        } \
    } while (0)

// Kernel metadata
#define KERNEL_NAME "{{KERNEL_NAME}}"
#define NUM_WARPS {{NUM_WARPS}}
#define WARP_SIZE 32
#define BLOCK_SIZE_X (NUM_WARPS * WARP_SIZE)
#define SHARED_MEMORY {{SHARED_MEMORY}}

int main(int argc, char** argv) {
    printf("Standalone launcher for Triton kernel: {{KERNEL_NAME}}\n");
    printf("NOTE: This is a template launcher.\n");
    printf("For actual argument data, use the launch-specific harness.\n\n");

    CUDA_CHECK(cuInit(0));

    CUdevice device;
    CUcontext context;
    CUDA_CHECK(cuDeviceGet(&device, 0));
#if CUDA_VERSION >= 13000
    CUDA_CHECK(cuCtxCreate(&context, NULL, 0, device));
#else
    CUDA_CHECK(cuCtxCreate(&context, 0, device));
#endif

    const char* binary_path = "{{BINARY_PATH}}";
    CUmodule module;
    CUDA_CHECK(cuModuleLoad(&module, binary_path));
    printf("Loaded kernel from: %s\n", binary_path);

    CUfunction kernel;
    CUDA_CHECK(cuModuleGetFunction(&kernel, module, KERNEL_NAME));
    printf("Got kernel function: %s\n\n", KERNEL_NAME);
    printf("NOTE: This is a template. No arguments configured.\n");
    printf("Check for launch-specific harness files for actual replays.\n");

    cuModuleUnload(module);
    cuCtxDestroy(context);
    return 0;
}
