// Standalone harness for Triton kernel: {{KERNEL_NAME}}
// Launch ID: {{LAUNCH_ID}}
// Generated by Tracker with captured arguments
// Kernel hash: {{KERNEL_HASH}}

#include <cuda.h>
#include <cuda_runtime.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <unistd.h>
{{VALIDATION_INCLUDE}}

{{HELPER_FUNCTIONS}}

int main(int argc, char** argv) {
    printf("=== Standalone Harness for Triton Kernel ===\n");
    printf("Kernel: {{KERNEL_NAME}}\n");
    printf("Launch ID: {{LAUNCH_ID}}\n");
    printf("Grid: {{GRID}}\n");
    printf("Block: {{BLOCK}}\n");
    printf("Shared memory: {{SHARED_MEMORY}} bytes\n");
    printf("\n");

    // Initialize CUDA
    cuInit(0);
    CUdevice device;
    CUcontext context;
    cuDeviceGet(&device, 0);
#if CUDA_VERSION >= 13000
    cuCtxCreate(&context, NULL, 0, device);
#else
    cuCtxCreate(&context, 0, device);
#endif

    // Get executable directory
    char exe_path[1024];
    ssize_t len = readlink("/proc/self/exe", exe_path, sizeof(exe_path) - 1);
    if (len == -1) {
        fprintf(stderr, "Failed to get executable path\n");
        return 1;
    }
    exe_path[len] = '\0';
    char* last_slash = strrchr(exe_path, '/');
    if (last_slash) *last_slash = '\0';

    // Load module
    char fatbin_path[2048];
    snprintf(fatbin_path, sizeof(fatbin_path), "%s/{{FATBIN_FILENAME}}", exe_path);
    CUmodule module;
    CUresult load_result = cuModuleLoad(&module, fatbin_path);
    if (load_result != CUDA_SUCCESS) {
        const char* errStr;
        cuGetErrorString(load_result, &errStr);
        fprintf(stderr, "Failed to load fatbin: %s\n", errStr);
        return 1;
    }
    printf("Loaded module from: %s\n", fatbin_path);

    // Get kernel function
    CUfunction kernel_func;
    CUresult func_result = cuModuleGetFunction(&kernel_func, module, "{{KERNEL_NAME}}");
    if (func_result != CUDA_SUCCESS) {
        const char* errStr;
        cuGetErrorString(func_result, &errStr);
        fprintf(stderr, "Failed to get function: %s\n", errStr);
        return 1;
    }
    printf("Got kernel function: {{KERNEL_NAME}}\n");
{{SHARED_MEMORY_CONFIG}}
    // Initialize arguments
    printf("Initializing arguments:\n");
{{ARG_DECLARATIONS}}

{{ARG_LOADING_CALLS}}

    // Allocate Triton runtime scratch buffers based on metadata
    // These pointers may differ from Triton's original allocation, but are functionally equivalent.
    void* global_scratch = NULL;
    void* profile_scratch = NULL;
{{SCRATCH_ALLOCATION}}
    // Setup kernel arguments (user args + Triton runtime args)
    void* args[] = { {{ARG_POINTERS}}, &global_scratch, &profile_scratch };

    // Launch kernel
    printf("\nLaunching kernel...\n");
    CUresult launch_result = cuLaunchKernel(
        kernel_func,
        {{GRID_X}}, {{GRID_Y}}, {{GRID_Z}},
        {{BLOCK_X}}, {{BLOCK_Y}}, {{BLOCK_Z}},
        {{SHARED_MEMORY}}, 0, args, 0
    );
    if (launch_result != CUDA_SUCCESS) {
        const char* errStr;
        cuGetErrorString(launch_result, &errStr);
        fprintf(stderr, "Kernel launch failed: %s\n", errStr);
        return 1;
    }

    cuCtxSynchronize();
    printf("Kernel execution completed successfully\n");
{{VALIDATION_CODE}}

    // Cleanup
    printf("\nCleaning up...\n");
{{ARG_CLEANUP}}
{{SCRATCH_CLEANUP}}
    cuModuleUnload(module);
    cuCtxDestroy(context);

    printf("Done!\n");
    return 0;
}
